# -*- coding: utf-8 -*-
"""LangChain_ChromaDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElGZG0iRL61MfHIklHfm4t434RDi-mqv
"""

import os
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY"

# !pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# !pip install sentence-transformers

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_community.embeddings import HuggingFaceEmbeddings

# Initialize free HuggingFace embeddings
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

from langchain_core.documents import Document

# Create LangChain documents for IPL players

doc1 = Document(
        page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
        metadata={"team": "Royal Challengers Bangalore"}
    )
doc2 = Document(
        page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
        metadata={"team": "Mumbai Indians"}
    )
doc3 = Document(
        page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
        metadata={"team": "Chennai Super Kings"}
    )
doc4 = Document(
        page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
        metadata={"team": "Mumbai Indians"}
    )
doc5 = Document(
        page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
        metadata={"team": "Chennai Super Kings"}
    )

docs = [doc1, doc2, doc3, doc4, doc5]

vector_store = Chroma(
    embedding_function=OpenAIEmbeddings(),
    persist_directory='my_chroma_db',
    collection_name='sample'
)

vector_store = Chroma(
    embedding_function=embeddings,
    persist_directory='my_chroma_db_free',
    collection_name='sample_free'
)
print("Vector store initialized with free embeddings.")

# Use the newly initialized free vector_store
vector_store.add_documents(docs)
print("Documents added to the free vector store.")

# view documents
vector_store.get(include=['embeddings','documents', 'metadatas'])

# search with similarity score using the free model
results = vector_store.similarity_search_with_score(
    query='Who among these are a bowler?',
    k=2
)
results

# meta-data filtering
vector_store.similarity_search_with_score(
    query="",
    filter={"team": "Chennai Super Kings"}
)

# Update logic: Note that IDs in Chroma are typically generated during add_documents
# Let's get the ID of the first document to demonstrate an update
all_docs = vector_store.get()
if all_docs['ids']:
    target_id = all_docs['ids'][0]
    updated_doc1 = Document(
        page_content="Virat Kohli, the former captain of RCB, is renowned for his aggressive leadership and consistent batting. He holds the record for most runs in IPL history.",
        metadata={"team": "Royal Challengers Bangalore"}
    )
    vector_store.update_document(document_id=target_id, document=updated_doc1)
    print(f"Updated document with ID: {target_id}")

# view documents
vector_store.get(include=['embeddings','documents', 'metadatas'])

# delete document
vector_store.delete(ids=[''])

# view documents
vector_store.get(include=['embeddings','documents', 'metadatas'])

