# -*- coding: utf-8 -*-
"""Rag Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpy7OC68iyABd2fTZBPDBI2eUStmQH3G
"""

# from google.colab import userdata
# import os
# GOOGLE_API_KEY = userdata.get('*****************************')
# os.environ["**************************************"] = GOOGLE_API_KEY

"""# Install libraries"""

!pip install -U sentence-transformers faiss-cpu langchain-community

!pip install -U langchain-cerebras

!pip install -U langchain-text-splitters langchain-community langchain-google-genai

"""# Step 1(a) - Indexing (Document Ingestion)"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
# from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

# Import the main YouTubeTranscriptApi class
from youtube_transcript_api import YouTubeTranscriptApi

# Import the exception that occurs when a video has captions disabled
from youtube_transcript_api._errors import TranscriptsDisabled


# ---------------------------------------------------------
# STEP 1: Get the YouTube Video ID
# ---------------------------------------------------------

# Only write the Video ID here.
# Do NOT write the complete YouTube URL.
#
# YouTube URL:
# https://youtu.be/Kbk9BiPhm7o?si=zRA6O6j_UXIu0tik
#
# Video ID:
# Kbk9BiPhm7o

video_id = "Kbk9BiPhm7o"


# ---------------------------------------------------------
# STEP 2: Try to retrieve the transcript
# ---------------------------------------------------------

try:

    # Create an object of YouTubeTranscriptApi.
    #
    # In the newer versions of youtube-transcript-api,
    # get_transcript() is no longer used as a class method.
    api = YouTubeTranscriptApi()


    # -----------------------------------------------------
    # STEP 3: Fetch the transcript
    # -----------------------------------------------------

    # fetch() retrieves the transcript/captions of the video.
    #
    # video_id:
    #     The ID of the YouTube video.
    #
    # languages=["en"]:
    #     We are asking for an English transcript.
    #
    # If an English transcript is available, it will be returned.
    transcript_list = api.fetch(
        video_id,
        languages=["en"]
    )


    # -----------------------------------------------------
    # STEP 4: Convert transcript into plain text
    # -----------------------------------------------------

    # The transcript contains multiple small caption chunks.
    #
    # For example:
    #
    # [
    #     FetchedTranscriptSnippet(text="Hello", ...),
    #     FetchedTranscriptSnippet(text="everyone", ...),
    #     FetchedTranscriptSnippet(text="welcome", ...)
    # ]
    #
    # Each chunk has a .text attribute.
    #
    # " ".join(...) combines all the individual chunks
    # into one complete string.

    transcript = " ".join(
        chunk.text
        for chunk in transcript_list
    )


    # -----------------------------------------------------
    # STEP 5: Print the final transcript
    # -----------------------------------------------------

    print(transcript)


# ---------------------------------------------------------
# STEP 6: Handle captions-disabled error
# ---------------------------------------------------------

except TranscriptsDisabled:

    # This error occurs when the YouTube video does not
    # have captions/transcripts available.
    print("No captions available for this video.")


# ---------------------------------------------------------
# STEP 7: Handle any other error
# ---------------------------------------------------------

except Exception as e:

    # Catch any other error and display it.
    #
    # For example:
    # - Invalid video ID
    # - Network problem
    # - Transcript unavailable
    # - Language not available
    # - YouTube blocking the request
    #
    print(f"Error retrieving transcript: {e}")

transcript_list

"""# Step 1(b) - Indexing (Text Splitting)"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

len(chunks)

chunks[100]

"""# Step 1(c) & 1(d) - Indexing (Embedding Generation and Storing in Vector Store)"""

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vector_store = FAISS.from_documents(
    chunks,
    embeddings
)

print("Vector store created successfully!")

vector_store.index_to_docstore_id

"""# Step 2 - Retrieval"""

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 10})

retriever

retriever.invoke('What is deepmind')

"""# Step 3 - Augmentation"""

from google.colab import userdata
import os

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"
)

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

question = "What is BCI?"

retrieved_docs = retriever.invoke(question)

print(retrieved_docs)

# 1. Combine retrieved chunks
context_text = "\n\n".join(
    doc.page_content for doc in retrieved_docs
)
context_text

# 2. Create the final prompt
final_prompt = prompt.invoke({
    "context": context_text,
    "question": question
})

final_prompt

"""# Step 4 - Generation"""

# 3. Send prompt to LLM
response = llm.invoke(final_prompt)

# 4. Display answer
print(response.content)

"""# Building a Chain

"""

from langchain_core.runnables import (
    RunnableParallel,
    RunnablePassthrough,
    RunnableLambda
)

from langchain_core.output_parsers import StrOutputParser


def format_docs(retrieved_docs):
    context_text = "\n\n".join(
        doc.page_content for doc in retrieved_docs
    )
    return context_text


parallel_chain = RunnableParallel({
    "context": retriever | RunnableLambda(format_docs),
    "question": RunnablePassthrough()
})

result = parallel_chain.invoke("Summarize the video?")

print(result)

parser = StrOutputParser()

main_chain = parallel_chain | prompt | llm | parser

main_chain.invoke('What is BCI?')

main_chain.invoke('Who is Elon mask?')

