# -*- coding: utf-8 -*-
"""AI Agent In LanChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193EarTP9cvZXNprAQ2joAZKj-R7nGXLp
"""

!pip install -q langchain-openai langchain-community langchain-core requests duckduckgo-search

pip install -U ddgs

!pip install -q langchain-ollama

# 1. Install zstd (required by Ollama installer) and then download Ollama
!sudo apt-get update && sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

# 2. Start Ollama server in the background
# It's important to run this in the background using `nohup` and `&`
# to prevent it from blocking the Colab kernel.
import subprocess

# Check if Ollama is already running
try:
    subprocess.run(['ollama', 'list'], check=True, capture_output=True)
    print("Ollama server is already running.")
except (subprocess.CalledProcessError, FileNotFoundError):
    print("Starting Ollama server...")
    # Use Popen to start in background and suppress output
    process = subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print(f"Ollama server started with PID: {process.pid}")

# Give Ollama a moment to start up
import time
time.sleep(5)

# 3. Download the qwen2.5:7b model (this might take a while)
!ollama pull qwen2.5:7b

"""Now that Ollama server is running and the model is pulled, you can try invoking the llm_with_tools again."""

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
import requests

from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

results = search_tool.invoke('top news in india today')

results

@tool
def get_weather_data(city: str) -> str:
  """
  This function fetches the current weather data for a given city
  """
  url = f'https://api.weatherstack.com/current?access_key=485c1c10a1d05b9b909a3e30703b2725&query={city}'

  response = requests.get(url)

  return response.json()

from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="qwen2.5:7b"
)

llm.invoke('hi')

from langchain.agents import create_agent

# Step 2: Pull the ReAct prompt from LangChain Hub
system_prompt = """
You are a helpful assistant.
You can use the available tools to answer questions.
Think carefully before using a tool.
"""

# Step 3: Create the ReAct agent manually with the pulled prompt
agent = create_agent(
    model=llm,
    tools=[search_tool, get_weather_data],
    system_prompt=system_prompt
)

response = agent.invoke({
    "messages": [
        {
            "role": "user",
            "content": "What is the weather today?"
        }
    ]
})

print(response)

response = agent.invoke({
    "messages": [
        {
            "role": "user",
            "content": "Find the capital of Madhya Pradesh, then find its current weather condition"
        }
    ]
})

print(response)

response["messages"][-1].content

question = "Find the capital of Madhya Pradesh, then find its current weather condition"

for chunk in agent.stream(
    {
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    },
    stream_mode="updates"
):
    for node, data in chunk.items():
        print(f"\n--- {node} ---")
        print(data)

import langchain
print(langchain.__version__)