# -*- coding: utf-8 -*-
"""Currency Conversion Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz3I0DoXZXCT_m_kqZDPuv7j2SyROSic

# Install/Upgrade LangChain packages
!pip install --upgrade langchain langchain-community langchain-core
# Restart your Colab runtime (Runtime -> Restart runtime) after this cell finishes if you continue to see import errors.
"""

!pip install --upgrade langchain langchain-community langchain-core

import requests
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, ToolMessage

import requests
from langchain_core.tools import tool
from typing import Annotated
from langchain_core.tools import InjectedToolArg
@tool
def get_conversion_factor(base_currency: str, target_currency: str) -> float:
  """
    This function fetches the currency conversion factor between a given base currency and a target currency.
  """
  url = f"https://v6.exchangerate-api.com/v6/e4415741389c36de9becc09d/pair/{base_currency}/{target_currency}"
  response = requests.get(url)

  return response.json()

@tool
def convert(base_currency_value: int, conversion_rate: Annotated[float, "The conversion rate"]) -> float:
  """
  Given a currency conversion rate this function calculates the target currency value from a given base currency value.
  """
  return base_currency_value * conversion_rate

# Check

base_currency = 'USD'
target_currency = 'INR'
url = f"https://v6.exchangerate-api.com/v6/e4415741389c36de9becc09d/pair/{base_currency}/{target_currency}"
response = requests.get(url)

print(f"API Request URL: {url}")
print(f"Response Status Code: {response.status_code}")
print(f"Raw Response Text: {response.text}")

if response.status_code == 200:
    try:
        print(f"Parsed JSON: {response.json()}")
    except Exception as e:
        print(f"Error decoding JSON despite 200 status: {e}")
else:
    print("API call failed with non-200 status code. Cannot parse JSON.")

convert.invoke({'base_currency_value':10, 'conversion_rate':85.16})

"""# Tool Binding

Install and Run Ollama Server
To use ChatOllama in Google Colab, you need to first install and run the Ollama server. This involves downloading the Ollama binary, making it executable, and then starting it in the background.
"""

# 1. Install zstd (required by Ollama installer) and then download Ollama
!sudo apt-get update && sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

# 2. Start Ollama server in the background
# It's important to run this in the background using `nohup` and `&`
# to prevent it from blocking the Colab kernel.
import subprocess

# Check if Ollama is already running
try:
    subprocess.run(['ollama', 'list'], check=True, capture_output=True)
    print("Ollama server is already running.")
except (subprocess.CalledProcessError, FileNotFoundError):
    print("Starting Ollama server...")
    # Use Popen to start in background and suppress output
    process = subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print(f"Ollama server started with PID: {process.pid}")

# Give Ollama a moment to start up
import time
time.sleep(5)

# 3. Download the qwen2.5:7b model (this might take a while)
!ollama pull qwen2.5:7b

"""Now that Ollama server is running and the model is pulled, you can try invoking the llm_with_tools again."""

!pip install -q langchain-ollama

from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="qwen2.5:7b"
)

llm_with_tools = llm.bind_tools([get_conversion_factor, convert])

messages = [HumanMessage('What is the conversion factor between INR and USD, and based on that can you convert 10 inr to usd')]

messages

ai_message = llm_with_tools.invoke(messages)

ai_message

messages.append(ai_message)

ai_message.tool_calls

for tool_call in ai_message.tool_calls:
  print(tool_call)

import json

for tool_call in ai_message.tool_calls:
  # execute the 1st tool and get the value of conversion rate
  if tool_call['name'] == 'get_conversion_factor':
    tool_message1 = get_conversion_factor.invoke(tool_call)
    # fetch this conversion rate
    conversion_rate = json.loads(tool_message1.content)['conversion_rate']
    # append this tool message to messages list
    messages.append(tool_message1)
  # execute the 2nd tool using the conversion rate from tool 1
  if tool_call['name'] == 'convert':
    # fetch the current arg
    tool_call['args']['conversion_rate'] = conversion_rate
    tool_message2 = convert.invoke(tool_call)
    messages.append(tool_message2)

messages

llm_with_tools.invoke(messages)

llm_with_tools.invoke(messages).content

from langchain_classic.agents import create_tool_calling_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate

# Prompt
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant that uses tools to answer questions."),
    ("human", "{input}"),
    ("placeholder", "{agent_scratchpad}"),
])

# Create agent
agent = create_tool_calling_agent(
    llm=llm,
    tools=[get_conversion_factor, convert],
    prompt=prompt
)

# Create executor
agent_executor = AgentExecutor(
    agent=agent,
    tools=[get_conversion_factor, convert],
    verbose=True
)

response = agent_executor.invoke({
    "input": "Hi, how are you?"
})

print(response["output"])