# -*- coding: utf-8 -*-
"""ToolCalling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jYcdhHwP7ZIVCifAwuKEw-8Spph7xmo
"""

!pip install -q langchain-openai langchain-core requests

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, ToolMessage
import requests

# tool create

@tool
def multiply(a: int, b: int) -> int:
  """Given 2 numbers a and b this tool returns their product"""
  return a * b

print(multiply.invoke({'a':3, 'b': 5}))

multiply.name

multiply.description

multiply.args

multiply.args_schema

"""# Tool Binding"""

!pip install -q langchain-ollama
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="qwen2.5:7b"
)

llm_with_tools = llm.bind_tools([multiply])

"""### Install and Run Ollama Server

To use `ChatOllama` in Google Colab, you need to first install and run the Ollama server. This involves downloading the Ollama binary, making it executable, and then starting it in the background.
"""

# 1. Install zstd (required by Ollama installer) and then download Ollama
!sudo apt-get update && sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

# 2. Start Ollama server in the background
# It's important to run this in the background using `nohup` and `&`
# to prevent it from blocking the Colab kernel.
import subprocess

# Check if Ollama is already running
try:
    subprocess.run(['ollama', 'list'], check=True, capture_output=True)
    print("Ollama server is already running.")
except (subprocess.CalledProcessError, FileNotFoundError):
    print("Starting Ollama server...")
    # Use Popen to start in background and suppress output
    process = subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print(f"Ollama server started with PID: {process.pid}")

# Give Ollama a moment to start up
import time
time.sleep(5)

"""After the server starts, you'll need to download the specific model you want to use (e.g., `qwen2.5:7b`)."""

# 3. Download the qwen2.5:7b model (this might take a while)
!ollama pull qwen2.5:7b

"""Now that Ollama server is running and the model is pulled, you can try invoking the `llm_with_tools` again.

# Tool Calling
"""

llm_with_tools.invoke('Hi how are you')

query = HumanMessage('can you multiply 3 with 1000')

# Start with just the initial human query
messages = [query]

messages

llm_with_tools.invoke(messages)

result = llm_with_tools.invoke('What is 3 times 5').tool_calls

result[0]

result[0]['args']

# First, invoke the LLM with the human query
ai_response = llm_with_tools.invoke(messages)
messages.append(ai_response)

# If the AI's response includes tool calls, execute them
if ai_response.tool_calls:
    for tool_call in ai_response.tool_calls:
        # Assuming only 'multiply' tool is available and expecting 'a' and 'b' args
        tool_output = multiply.invoke(tool_call['args'])
        messages.append(ToolMessage(tool_output, tool_call_id=tool_call['id'], name=tool_call['name']))

messages

"""# Tool Execution"""

multiply.invoke(result[0]['args'])

# TOOL Message
multiply.invoke({'name': 'multiply',
 'args': {'a': 3, 'b': 5},
 'id': 'a28c8a9a-cada-4948-ae9a-f73e38577f15',
 'type': 'tool_call'})

# This cell is no longer needed in the corrected flow, as tool invocation is now handled above.

tool_result

# This cell is no longer needed as tool output appending is handled above.

messages

# Now, invoke the LLM again with the updated messages, including tool calls and their results
final_response = llm_with_tools.invoke(messages)
print(final_response.content)

llm_with_tools.invoke(messages).content

