# -*- coding: utf-8 -*-
"""Langchain_Runnable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14diadg21LogTowZSoscgcVw0C8P3ubMB
"""

import random

class llm:

  def __init__(self):
    print('LLM Created')

  def predict(self, prompt):

    response_list = [
        'Delhi is the capital of India',
        'IPL is a cricket league',
        'AI stands for Artificial Intelligence'
    ]

    return {'response': random.choice(response_list)}

first_llm_instance = llm()

first_llm_instance.predict('What is the capital of India?')

class NakliPromptTemplate:

  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def format(self, input_dict):
    return self.template.format(**input_dict)

template = NakliPromptTemplate(
    template='Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

prompt = template.format({'length':'short','topic':'india'})

prompt

llm2 = llm()

"""You can create multiple instances of the `llm` class by assigning them to different variable names. This ensures the `llm` class itself remains callable for new instances."""

my_llm_instance_1 = llm()
my_llm_instance_2 = llm()

print('First LLM instance prediction:')
display(my_llm_instance_1.predict('What is the capital of India?'))

print('\nSecond LLM instance prediction:')
display(my_llm_instance_2.predict('Tell me about IPL.'))

llm2.predict(prompt)

class NakliLLMChain:

  def __init__(self, llm, prompt):
    self.llm = llm
    self.prompt = prompt

  def run(self, input_dict):

    final_prompt = self.prompt.format(input_dict)
    result = self.llm.predict(final_prompt)

    return result['response']

template = NakliPromptTemplate(
    template='Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

llm = llm()

chain = NakliLLMChain(llm, template)

chain.run({'length':'short', 'topic': 'india'})

